version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rake db:migrate && bundle exec rails s -b '0.0.0.0' && bundle exec sidekiq"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/mini_coachy_development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  # PostgreSQL service
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_coachy_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
